version: '3'
services:
  blog:
    build: blog/
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb
  auth:
    build: auth/
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:3-xenial"
  nginx:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - blog
      - auth
